name: Update Railway Database

on:
  # Schedule the job to run
  schedule:
    - cron: "0 0 * * *"  # Runs once a day at midnight UTC
  workflow_dispatch:  # Allows manual execution

jobs:
  update-database:
    runs-on: ubuntu-latest  # Running on Ubuntu

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # Checks out your repository's code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"  # Use Python 3.11 (adjust as needed)

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up environment variables
      run: |
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
        echo "DB_USER=${{ secrets.DB_USER }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
        echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
        echo "NEWS_API_KEY=${{ secrets.NEWS_API_KEY }}" >> .env

    - name: Run Data Pipeline to Update Railway DB
      run: python3 run_pipeline.py
